name: speech_to_text_
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  get: ^4.7.2
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  rename_app: ^1.6.5

# Configuration لـ flutter_launcher_icons (خارج flutter section)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_app.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/img/
    - assets/icon/  
